
math.pow = function(x, y)
    return x ^ y
end

print("ACRF10_avoidArea START SCRIPT ")

coalitionId = {
	["0"] = "neutral",
	["1"] = "red",
	["2"] = "blue",
}

coalitionIdNumeric = {
	[0] = "neutral",
	[1] = "red",
	[2] = "blue",
}

coalitionIdNumericENI = {
	[0] = 1,
	[1] = 2,
	[2] = 1,
}

--variable global
DCS_Side = {"blue", "red", "neutrals"}

DCS_ENI_Side = {
	["blue"] = "red",
	["red"] = "blue"
	}

-- Unit.Category = {
-- 	AIRPLANE      = 0,
-- 	HELICOPTER    = 1,
-- 	GROUND_UNIT   = 2,
-- 	SHIP          = 3,
-- 	STRUCTURE     = 4
--   }
DCS_CategoryById = {
	[0] = Airplane,
	[1] = Helicopters,

}

camp = {
["groundthreats"] = 
{
    ["blue"] = 
    {
        [1] = 
        {
            ["SEAD_offset"] = 1,
            ["class"] = "SAM",
            ["elevation"] = 2.5,
            ["hidden"] = false,
            ["level"] = 5,
            ["max_alt"] = 3600,
            ["min_alt"] = 0,
            ["name"] = "Unit #061",
            ["night"] = true,
            ["range"] = 10000,
            ["type"] = "rapier_fsa_blindfire_radar",
            ["x"] = 76610.214859726,
            ["y"] = -23712.168354482,
        },
        [2] = 
        {
            ["SEAD_offset"] = 2,
            ["class"] = "SAM",
            ["elevation"] = 3,
            ["hidden"] = true,
            ["level"] = 7,
            ["max_alt"] = 59000,
            ["min_alt"] = 0,
            ["name"] = "Unit #444",
            ["night"] = true,
            ["range"] = 46000,
            ["type"] = "Hawk tr",
            ["x"] = 83377.28665956,
            ["y"] = -15136.993722528,
        },
        [3] = 
        {
            ["SEAD_offset"] = 2,
            ["class"] = "SAM",
            ["elevation"] = 3,
            ["hidden"] = true,
            ["level"] = 7,
            ["max_alt"] = 59000,
            ["min_alt"] = 0,
            ["name"] = "Unit #468",
            ["night"] = true,
            ["range"] = 46000,
            ["type"] = "Hawk tr",
            ["x"] = 169839.92368744,
            ["y"] = -178103.82197734,
        },
        [4] = 
        {
            ["SEAD_offset"] = 1,
            ["class"] = "SAM",
            ["elevation"] = 2.5,
            ["hidden"] = false,
            ["level"] = 5,
            ["max_alt"] = 3600,
            ["min_alt"] = 0,
            ["name"] = "Unit #402",
            ["night"] = true,
            ["range"] = 10000,
            ["type"] = "rapier_fsa_blindfire_radar",
            ["x"] = 137478.33321232,
            ["y"] = -5758.1539702585,
        },
        [5] = 
        {
            ["SEAD_offset"] = 1,
            ["class"] = "SAM",
            ["elevation"] = 2.5,
            ["hidden"] = false,
            ["level"] = 5,
            ["max_alt"] = 3600,
            ["min_alt"] = 0,
            ["name"] = "Unit #424",
            ["night"] = true,
            ["range"] = 10000,
            ["type"] = "rapier_fsa_blindfire_radar",
            ["x"] = 117038.48676022,
            ["y"] = 4295.1602516269,
        },
        [6] = 
        {
            ["SEAD_offset"] = 2,
            ["class"] = "SAM",
            ["elevation"] = 3,
            ["hidden"] = true,
            ["level"] = 7,
            ["max_alt"] = 59000,
            ["min_alt"] = 0,
            ["name"] = "Unit #610",
            ["night"] = true,
            ["range"] = 46000,
            ["type"] = "Hawk tr",
            ["x"] = 380526.4176597,
            ["y"] = -340878.36392021,
        },
        [7] = 
        {
            ["SEAD_offset"] = 1,
            ["class"] = "SAM",
            ["elevation"] = 2.5,
            ["hidden"] = false,
            ["level"] = 5,
            ["max_alt"] = 3600,
            ["min_alt"] = 0,
            ["name"] = "Shiraz International Airport Defense-1-1",
            ["night"] = true,
            ["range"] = 10000,
            ["type"] = "rapier_fsa_blindfire_radar",
            ["x"] = 380991.5223953,
            ["y"] = -350294.07571086,
        },
        [8] = 
        {
            ["SEAD_offset"] = 1,
            ["class"] = "SAM",
            ["elevation"] = 2.5,
            ["hidden"] = false,
            ["level"] = 5,
            ["max_alt"] = 3600,
            ["min_alt"] = 0,
            ["name"] = "Unit #179",
            ["night"] = true,
            ["range"] = 10000,
            ["type"] = "rapier_fsa_blindfire_radar",
            ["x"] = 111577.98944934,
            ["y"] = -37461.631541381,
        },
        [9] = 
        {
            ["SEAD_offset"] = 2,
            ["class"] = "SAM",
            ["elevation"] = 3,
            ["hidden"] = true,
            ["level"] = 7,
            ["max_alt"] = 59000,
            ["min_alt"] = 0,
            ["name"] = "Unit #432",
            ["night"] = true,
            ["range"] = 46000,
            ["type"] = "Hawk tr",
            ["x"] = 73750.249158947,
            ["y"] = 8651.9575348772,
        },
        [10] = 
        {
            ["SEAD_offset"] = 2,
            ["class"] = "SAM",
            ["elevation"] = 3,
            ["hidden"] = true,
            ["level"] = 7,
            ["max_alt"] = 59000,
            ["min_alt"] = 0,
            ["name"] = "Unit #456",
            ["night"] = true,
            ["range"] = 46000,
            ["type"] = "Hawk tr",
            ["x"] = 122205.2533373,
            ["y"] = -23850.117348694,
        },
        [11] = 
        {
            ["SEAD_offset"] = 1,
            ["class"] = "SAM",
            ["elevation"] = 2.5,
            ["hidden"] = false,
            ["level"] = 5,
            ["max_alt"] = 3600,
            ["min_alt"] = 0,
            ["name"] = "Bandar Abbas Airbase Defenses-1-1",
            ["night"] = true,
            ["range"] = 10000,
            ["type"] = "rapier_fsa_blindfire_radar",
            ["x"] = 113531.66548052,
            ["y"] = 14061.51377384,
        },
        [12] = 
        {
            ["SEAD_offset"] = 1,
            ["class"] = "SAM",
            ["elevation"] = 2.5,
            ["hidden"] = false,
            ["level"] = 5,
            ["max_alt"] = 3600,
            ["min_alt"] = 0,
            ["name"] = "Havadarya Airbase Defenses-1-1",
            ["night"] = true,
            ["range"] = 10000,
            ["type"] = "rapier_fsa_blindfire_radar",
            ["x"] = 107101.34915526,
            ["y"] = -4423.9377993109,
        },
        [13] = 
        {
            ["SEAD_offset"] = 1,
            ["class"] = "SAM",
            ["elevation"] = 2.5,
            ["hidden"] = false,
            ["level"] = 5,
            ["max_alt"] = 3600,
            ["min_alt"] = 0,
            ["name"] = "Lar Airbase Defense-1-1",
            ["night"] = true,
            ["range"] = 10000,
            ["type"] = "rapier_fsa_blindfire_radar",
            ["x"] = 168561.48501934,
            ["y"] = -183644.34646083,
        },
        [14] = 
        {
            ["SEAD_offset"] = 1,
            ["class"] = "SAM",
            ["elevation"] = 2.5,
            ["hidden"] = false,
            ["level"] = 5,
            ["max_alt"] = 3600,
            ["min_alt"] = 0,
            ["name"] = "Bandar Abbas Airbase Defenses-2-1",
            ["night"] = true,
            ["range"] = 10000,
            ["type"] = "rapier_fsa_blindfire_radar",
            ["x"] = 118889.09149636,
            ["y"] = 15645.786415833,
        },
        [15] = 
        {
            ["SEAD_offset"] = 1,
            ["class"] = "SAM",
            ["elevation"] = 2.5,
            ["hidden"] = false,
            ["level"] = 5,
            ["max_alt"] = 3600,
            ["min_alt"] = 0,
            ["name"] = "Unit #623",
            ["night"] = true,
            ["range"] = 10000,
            ["type"] = "rapier_fsa_blindfire_radar",
            ["x"] = 95611.98698385,
            ["y"] = 23731.94439594,
        },
        [16] = 
        {
            ["SEAD_offset"] = 1,
            ["class"] = "SAM",
            ["elevation"] = 2.5,
            ["hidden"] = false,
            ["level"] = 5,
            ["max_alt"] = 3600,
            ["min_alt"] = 0,
            ["name"] = "Unit #413",
            ["night"] = true,
            ["range"] = 10000,
            ["type"] = "rapier_fsa_blindfire_radar",
            ["x"] = 98710.438316912,
            ["y"] = 18638.430937297,
        },
        [17] = 
        {
            ["SEAD_offset"] = 0,
            ["class"] = "SAM",
            ["elevation"] = 1.5,
            ["hidden"] = false,
            ["level"] = 5,
            ["max_alt"] = 3600,
            ["min_alt"] = 0,
            ["name"] = "Unit #414",
            ["night"] = false,
            ["range"] = 8500,
            ["type"] = "rapier_fsa_optical_tracker_unit",
            ["x"] = 98692.453841444,
            ["y"] = 18635.333837032,
        },
    },
    ["red"] = 
    {
        [1] = 
        {
            ["SEAD_offset"] = 0,
            ["class"] = "AAA",
            ["elevation"] = 3.5,
            ["hidden"] = true,
            ["level"] = 1,
            ["max_alt"] = 4300,
            ["min_alt"] = 0,
            ["name"] = "Unit #327",
            ["night"] = true,
            ["range"] = 5000,
            ["type"] = "ZSU_57_2",
            ["x"] = -92142.861592425,
            ["y"] = -73506.671066373,
        },
        [2] = 
        {
            ["SEAD_offset"] = 0,
            ["class"] = "AAA",
            ["elevation"] = 3.5,
            ["hidden"] = true,
            ["level"] = 1,
            ["max_alt"] = 4300,
            ["min_alt"] = 0,
            ["name"] = "Unit #019",
            ["night"] = true,
            ["range"] = 5000,
            ["type"] = "ZSU_57_2",
            ["x"] = 63643.433255344,
            ["y"] = -23034.197062249,
        },
        [3] = 
        {
            ["SEAD_offset"] = 0,
            ["class"] = "AAA",
            ["elevation"] = 3.5,
            ["hidden"] = true,
            ["level"] = 1,
            ["max_alt"] = 4300,
            ["min_alt"] = 0,
            ["name"] = "Unit #358",
            ["night"] = true,
            ["range"] = 5000,
            ["type"] = "ZSU_57_2",
            ["x"] = -140874.73282822,
            ["y"] = -108617.79309562,
        },
        [4] = 
        {
            ["SEAD_offset"] = 0,
            ["class"] = "AAA",
            ["elevation"] = 3.5,
            ["hidden"] = true,
            ["level"] = 1,
            ["max_alt"] = 4300,
            ["min_alt"] = 0,
            ["name"] = "Unit #359",
            ["night"] = true,
            ["range"] = 5000,
            ["type"] = "ZSU_57_2",
            ["x"] = -140667.87413312,
            ["y"] = -111218.30240545,
        },
        [5] = 
        {
            ["SEAD_offset"] = 0,
            ["class"] = "AAA",
            ["elevation"] = 3.5,
            ["hidden"] = true,
            ["level"] = 1,
            ["max_alt"] = 4300,
            ["min_alt"] = 0,
            ["name"] = "Unit #360",
            ["night"] = true,
            ["range"] = 5000,
            ["type"] = "ZSU_57_2",
            ["x"] = -140170.19328338,
            ["y"] = -110259.06793754,
        },
        [6] = 
        {
            ["SEAD_offset"] = 0,
            ["class"] = "AAA",
            ["elevation"] = 3.5,
            ["hidden"] = true,
            ["level"] = 1,
            ["max_alt"] = 4300,
            ["min_alt"] = 0,
            ["name"] = "Unit #373",
            ["night"] = true,
            ["range"] = 5000,
            ["type"] = "ZSU_57_2",
            ["x"] = -213048.80209792,
            ["y"] = -173449.02301013,
        },
        [7] = 
        {
            ["SEAD_offset"] = 0,
            ["class"] = "AAA",
            ["elevation"] = 3.5,
            ["hidden"] = true,
            ["level"] = 1,
            ["max_alt"] = 4300,
            ["min_alt"] = 0,
            ["name"] = "Unit #374",
            ["night"] = true,
            ["range"] = 5000,
            ["type"] = "ZSU_57_2",
            ["x"] = -210716.93083467,
            ["y"] = -172538.01342148,
        },
        [8] = 
        {
            ["SEAD_offset"] = 0,
            ["class"] = "AAA",
            ["elevation"] = 3.5,
            ["hidden"] = true,
            ["level"] = 1,
            ["max_alt"] = 4300,
            ["min_alt"] = 0,
            ["name"] = "Unit #372",
            ["night"] = true,
            ["range"] = 5000,
            ["type"] = "ZSU_57_2",
            ["x"] = -211606.80142605,
            ["y"] = -173867.86307142,
        },
        [9] = 
        {
            ["SEAD_offset"] = 1,
            ["class"] = "SAM",
            ["elevation"] = 5.5,
            ["hidden"] = true,
            ["level"] = 7,
            ["max_alt"] = 7000,
            ["min_alt"] = 0,
            ["name"] = "Unit #392",
            ["night"] = true,
            ["range"] = 15000,
            ["type"] = "Osa 9A33 ln",
            ["x"] = 72144.902072264,
            ["y"] = -98685.201266472,
        },
        [10] = 
        {
            ["SEAD_offset"] = 2,
            ["class"] = "SAM",
            ["elevation"] = 3,
            ["hidden"] = true,
            ["level"] = 5,
            ["max_alt"] = 20000,
            ["min_alt"] = 50,
            ["name"] = "DontPrune Unit #477",
            ["night"] = true,
            ["range"] = 45000,
            ["type"] = "SNR_75V",
            ["x"] = -77235.009189999,
            ["y"] = -70543.118988837,
        },
        [11] = 
        {
            ["SEAD_offset"] = 2,
            ["class"] = "SAM",
            ["elevation"] = 3,
            ["hidden"] = true,
            ["level"] = 5,
            ["max_alt"] = 20000,
            ["min_alt"] = 50,
            ["name"] = "Unit #495",
            ["night"] = true,
            ["range"] = 45000,
            ["type"] = "SNR_75V",
            ["x"] = -100607.20269532,
            ["y"] = -204326.29732957,
        },
        [12] = 
        {
            ["SEAD_offset"] = 2,
            ["class"] = "SAM",
            ["elevation"] = 3,
            ["hidden"] = true,
            ["level"] = 5,
            ["max_alt"] = 20000,
            ["min_alt"] = 50,
            ["name"] = "DontPrune Unit #513",
            ["night"] = true,
            ["range"] = 45000,
            ["type"] = "SNR_75V",
            ["x"] = 4999.7651915443,
            ["y"] = -4246.0983609686,
        },
        [13] = 
        {
            ["SEAD_offset"] = 0,
            ["class"] = "AAA",
            ["elevation"] = 3.5,
            ["hidden"] = true,
            ["level"] = 1,
            ["max_alt"] = 4300,
            ["min_alt"] = 0,
            ["name"] = "Unit #039",
            ["night"] = true,
            ["range"] = 5000,
            ["type"] = "ZSU_57_2",
            ["x"] = 64204.763920043,
            ["y"] = -30064.6667384,
        },
        [14] = 
        {
            ["SEAD_offset"] = 0,
            ["class"] = "AAA",
            ["elevation"] = 3.5,
            ["hidden"] = true,
            ["level"] = 1,
            ["max_alt"] = 4300,
            ["min_alt"] = 0,
            ["name"] = "Unit #021",
            ["night"] = true,
            ["range"] = 5000,
            ["type"] = "ZSU_57_2",
            ["x"] = 63815.050470992,
            ["y"] = -29605.55363197,
        },
        [15] = 
        {
            ["SEAD_offset"] = 0,
            ["class"] = "AAA",
            ["elevation"] = 3.5,
            ["hidden"] = true,
            ["level"] = 1,
            ["max_alt"] = 4300,
            ["min_alt"] = 0,
            ["name"] = "Unit #038",
            ["night"] = true,
            ["range"] = 5000,
            ["type"] = "ZSU_57_2",
            ["x"] = 64166.37875685,
            ["y"] = -29775.132936033,
        },
        [16] = 
        {
            ["SEAD_offset"] = 2,
            ["class"] = "SAM",
            ["elevation"] = 3,
            ["hidden"] = true,
            ["level"] = 5,
            ["max_alt"] = 20000,
            ["min_alt"] = 50,
            ["name"] = "DontPrune Unit #531",
            ["night"] = true,
            ["range"] = 45000,
            ["type"] = "SNR_75V",
            ["x"] = 69798.619432226,
            ["y"] = -76895.511607505,
        },
        [17] = 
        {
            ["SEAD_offset"] = 2,
            ["class"] = "SAM",
            ["elevation"] = 3,
            ["hidden"] = true,
            ["level"] = 5,
            ["max_alt"] = 20000,
            ["min_alt"] = 50,
            ["name"] = "Unit #549",
            ["night"] = true,
            ["range"] = 45000,
            ["type"] = "SNR_75V",
            ["x"] = 42521.564468423,
            ["y"] = -224302.68469048,
        },
        [18] = 
        {
            ["SEAD_offset"] = 2,
            ["class"] = "SAM",
            ["elevation"] = 3,
            ["hidden"] = true,
            ["level"] = 6,
            ["max_alt"] = 20000,
            ["min_alt"] = 50,
            ["name"] = "Unit #567",
            ["night"] = true,
            ["range"] = 23000,
            ["type"] = "snr s-125 tr",
            ["x"] = -161608.55086858,
            ["y"] = -136614.68159044,
        },
        [19] = 
        {
            ["SEAD_offset"] = 2,
            ["class"] = "SAM",
            ["elevation"] = 3,
            ["hidden"] = true,
            ["level"] = 6,
            ["max_alt"] = 20000,
            ["min_alt"] = 50,
            ["name"] = "Unit #577",
            ["night"] = true,
            ["range"] = 23000,
            ["type"] = "snr s-125 tr",
            ["x"] = -120280.72855014,
            ["y"] = -75628.868495139,
        },
        [20] = 
        {
            ["SEAD_offset"] = 2,
            ["class"] = "SAM",
            ["elevation"] = 3,
            ["hidden"] = true,
            ["level"] = 6,
            ["max_alt"] = 20000,
            ["min_alt"] = 50,
            ["name"] = "Unit #587",
            ["night"] = true,
            ["range"] = 23000,
            ["type"] = "snr s-125 tr",
            ["x"] = 11803.627771405,
            ["y"] = -92800.899667261,
        },
        [21] = 
        {
            ["SEAD_offset"] = 2,
            ["class"] = "SAM",
            ["elevation"] = 3,
            ["hidden"] = true,
            ["level"] = 6,
            ["max_alt"] = 20000,
            ["min_alt"] = 50,
            ["name"] = "Unit #597",
            ["night"] = true,
            ["range"] = 23000,
            ["type"] = "snr s-125 tr",
            ["x"] = 114565.43490033,
            ["y"] = -90679.752306794,
        },
        [22] = 
        {
            ["SEAD_offset"] = 0,
            ["class"] = "AAA",
            ["elevation"] = 3.5,
            ["hidden"] = true,
            ["level"] = 1,
            ["max_alt"] = 4300,
            ["min_alt"] = 0,
            ["name"] = "Unit #009",
            ["night"] = true,
            ["range"] = 5000,
            ["type"] = "ZSU_57_2",
            ["x"] = 63797.685899887,
            ["y"] = -22627.140468637,
        },
        [23] = 
        {
            ["SEAD_offset"] = 0,
            ["class"] = "AAA",
            ["elevation"] = 3.5,
            ["hidden"] = true,
            ["level"] = 1,
            ["max_alt"] = 4300,
            ["min_alt"] = 0,
            ["name"] = "Unit #041",
            ["night"] = true,
            ["range"] = 5000,
            ["type"] = "ZSU_57_2",
            ["x"] = 63663.148411369,
            ["y"] = -30247.481916686,
        },
        [24] = 
        {
            ["SEAD_offset"] = 1,
            ["class"] = "SAM",
            ["elevation"] = 5.5,
            ["hidden"] = true,
            ["level"] = 7,
            ["max_alt"] = 7000,
            ["min_alt"] = 0,
            ["name"] = "Unit #701",
            ["night"] = true,
            ["range"] = 15000,
            ["type"] = "Osa 9A33 ln",
            ["x"] = 57474.12050958,
            ["y"] = -52087.029103149,
        },
        [25] = 
        {
            ["SEAD_offset"] = 1,
            ["class"] = "SAM",
            ["elevation"] = 5.5,
            ["hidden"] = true,
            ["level"] = 7,
            ["max_alt"] = 7000,
            ["min_alt"] = 0,
            ["name"] = "Unit #718-1",
            ["night"] = true,
            ["range"] = 15000,
            ["type"] = "Osa 9A33 ln",
            ["x"] = 66920.668510568,
            ["y"] = -42485.050903612,
        },
        [26] = 
        {
            ["SEAD_offset"] = 0,
            ["class"] = "AAA",
            ["elevation"] = 3.5,
            ["hidden"] = true,
            ["level"] = 1,
            ["max_alt"] = 4300,
            ["min_alt"] = 0,
            ["name"] = "3rd Iraqi Bat Artillery AA-1",
            ["night"] = true,
            ["range"] = 5000,
            ["type"] = "ZSU_57_2",
            ["x"] = 116385.98846027,
            ["y"] = -68092.872678191,
        },
        [27] = 
        {
            ["SEAD_offset"] = 0,
            ["class"] = "AAA",
            ["elevation"] = 3.5,
            ["hidden"] = true,
            ["level"] = 1,
            ["max_alt"] = 4300,
            ["min_alt"] = 0,
            ["name"] = "3rd Iraqi Bat Artillery AA-2",
            ["night"] = true,
            ["range"] = 5000,
            ["type"] = "ZSU_57_2",
            ["x"] = 116566.63402656,
            ["y"] = -68233.645707356,
        },
        [28] = 
        {
            ["SEAD_offset"] = 0,
            ["class"] = "AAA",
            ["elevation"] = 3.5,
            ["hidden"] = true,
            ["level"] = 1,
            ["max_alt"] = 4300,
            ["min_alt"] = 0,
            ["name"] = "9th Iraqi Inf Cie Reinforcement AA-2",
            ["night"] = true,
            ["range"] = 5000,
            ["type"] = "ZSU_57_2",
            ["x"] = 114840.08385208,
            ["y"] = -62160.050281189,
        },
        [29] = 
        {
            ["SEAD_offset"] = 0,
            ["class"] = "AAA",
            ["elevation"] = 3.5,
            ["hidden"] = true,
            ["level"] = 1,
            ["max_alt"] = 4300,
            ["min_alt"] = 0,
            ["name"] = "Unit #203",
            ["night"] = true,
            ["range"] = 5000,
            ["type"] = "ZSU_57_2",
            ["x"] = 104998.75865152,
            ["y"] = -48618.043181952,
        },
        [30] = 
        {
            ["SEAD_offset"] = 0,
            ["class"] = "AAA",
            ["elevation"] = 3.5,
            ["hidden"] = true,
            ["level"] = 1,
            ["max_alt"] = 4300,
            ["min_alt"] = 0,
            ["name"] = "Unit #205",
            ["night"] = true,
            ["range"] = 5000,
            ["type"] = "ZSU_57_2",
            ["x"] = 105222.16606697,
            ["y"] = -48794.31620231,
        },
        [31] = 
        {
            ["SEAD_offset"] = 0,
            ["class"] = "AAA",
            ["elevation"] = 3.5,
            ["hidden"] = true,
            ["level"] = 1,
            ["max_alt"] = 4300,
            ["min_alt"] = 0,
            ["name"] = "Unit #204",
            ["night"] = true,
            ["range"] = 5000,
            ["type"] = "ZSU_57_2",
            ["x"] = 105404.13890322,
            ["y"] = -49165.958566054,
        },
        [32] = 
        {
            ["SEAD_offset"] = 0,
            ["class"] = "AAA",
            ["elevation"] = 3.5,
            ["hidden"] = true,
            ["level"] = 1,
            ["max_alt"] = 4300,
            ["min_alt"] = 0,
            ["name"] = "Unit #207",
            ["night"] = true,
            ["range"] = 5000,
            ["type"] = "ZSU_57_2",
            ["x"] = 108437.88172532,
            ["y"] = -56679.964607793,
        },
        [33] = 
        {
            ["SEAD_offset"] = 0,
            ["class"] = "AAA",
            ["elevation"] = 3.5,
            ["hidden"] = true,
            ["level"] = 1,
            ["max_alt"] = 4300,
            ["min_alt"] = 0,
            ["name"] = "Unit #209",
            ["night"] = true,
            ["range"] = 5000,
            ["type"] = "ZSU_57_2",
            ["x"] = 108678.8447416,
            ["y"] = -56634.049206646,
        },
        [34] = 
        {
            ["SEAD_offset"] = 0,
            ["class"] = "AAA",
            ["elevation"] = 3.5,
            ["hidden"] = true,
            ["level"] = 1,
            ["max_alt"] = 4300,
            ["min_alt"] = 0,
            ["name"] = "Unit #214",
            ["night"] = true,
            ["range"] = 5000,
            ["type"] = "ZSU_57_2",
            ["x"] = 114238.15502814,
            ["y"] = -56879.623900927,
        },
        [35] = 
        {
            ["SEAD_offset"] = 0,
            ["class"] = "AAA",
            ["elevation"] = 3.5,
            ["hidden"] = true,
            ["level"] = 1,
            ["max_alt"] = 4300,
            ["min_alt"] = 0,
            ["name"] = "Unit #215",
            ["night"] = true,
            ["range"] = 5000,
            ["type"] = "ZSU_57_2",
            ["x"] = 114025.01774609,
            ["y"] = -56835.541290383,
        },
        [36] = 
        {
            ["SEAD_offset"] = 0,
            ["class"] = "AAA",
            ["elevation"] = 3.5,
            ["hidden"] = true,
            ["level"] = 1,
            ["max_alt"] = 4300,
            ["min_alt"] = 0,
            ["name"] = "Unit #217",
            ["night"] = true,
            ["range"] = 5000,
            ["type"] = "ZSU_57_2",
            ["x"] = 110143.75296834,
            ["y"] = -59218.211896626,
        },
        [37] = 
        {
            ["SEAD_offset"] = 0,
            ["class"] = "AAA",
            ["elevation"] = 3.5,
            ["hidden"] = true,
            ["level"] = 1,
            ["max_alt"] = 4300,
            ["min_alt"] = 0,
            ["name"] = "Unit #220",
            ["night"] = true,
            ["range"] = 5000,
            ["type"] = "ZSU_57_2",
            ["x"] = 118589.34146913,
            ["y"] = -61837.240104756,
        },
        [38] = 
        {
            ["SEAD_offset"] = 0,
            ["class"] = "AAA",
            ["elevation"] = 3.5,
            ["hidden"] = true,
            ["level"] = 1,
            ["max_alt"] = 4300,
            ["min_alt"] = 0,
            ["name"] = "Unit #226",
            ["night"] = true,
            ["range"] = 5000,
            ["type"] = "ZSU_57_2",
            ["x"] = 116903.54716448,
            ["y"] = -67306.416296057,
        },
        [39] = 
        {
            ["SEAD_offset"] = 0,
            ["class"] = "AAA",
            ["elevation"] = 3.5,
            ["hidden"] = true,
            ["level"] = 1,
            ["max_alt"] = 4300,
            ["min_alt"] = 0,
            ["name"] = "Unit #228",
            ["night"] = true,
            ["range"] = 5000,
            ["type"] = "ZSU_57_2",
            ["x"] = 117022.18229748,
            ["y"] = -67290.880487956,
        },
        [40] = 
        {
            ["SEAD_offset"] = 0,
            ["class"] = "AAA",
            ["elevation"] = 3.5,
            ["hidden"] = true,
            ["level"] = 1,
            ["max_alt"] = 4300,
            ["min_alt"] = 0,
            ["name"] = "Unit #690",
            ["night"] = true,
            ["range"] = 5000,
            ["type"] = "ZSU_57_2",
            ["x"] = -45385.768691326,
            ["y"] = -30501.272061534,
        },
        [41] = 
        {
            ["SEAD_offset"] = 0,
            ["class"] = "AAA",
            ["elevation"] = 3.5,
            ["hidden"] = true,
            ["level"] = 1,
            ["max_alt"] = 4300,
            ["min_alt"] = 0,
            ["name"] = "Unit #693",
            ["night"] = true,
            ["range"] = 5000,
            ["type"] = "ZSU_57_2",
            ["x"] = -45496.409294454,
            ["y"] = -30583.441629981,
        },
    },
},
}

print("ACRF10_avoidArea F1______ coalitionIdNumeric[blue] "..tostring(coalitionIdNumeric[2]))
print("ACRF10_avoidArea F2______ DCS_ENI_Side "..tostring(DCS_ENI_Side[coalitionIdNumeric[2]]))


local ENI_side = DCS_ENI_Side[coalitionIdNumeric[2]]
print("ACRF10_avoidArea F3______ ENI_side "..tostring(ENI_side))

currentPointXY = {
    ["x"] = 42621.564468423,
    ["y"] = -224402.68469048,
}
        
for threatN, threat in pairs(camp.groundthreats[ENI_side]) do
    
    if threat and threat.class and threat.class == "SAM"  then

        print("ACRF10_avoidArea F4______ threat.x "..tostring(threat.x).." currentPointXY "..tostring(currentPointXY.x))

        local distance = math.sqrt(math.pow(threat.x - currentPointXY.x, 2) + math.pow(threat.y - currentPointXY.y, 2))

        print("ACRF10_avoidArea I ______ _____ distance "..tostring(distance).." <= range? "..tostring(threat.range))

        if distance <= threat.range then

            print("ACRF10_avoidArea J ______ _____ name "..tostring(threat.name))

        end
    end
end

print("ACRF10_avoidArea FIN SCRIPT ")
